### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by vhoulbreque** [happyleavesaoc/python-voobly#1]
This is my code:

```python
from voobly import get_session, get_match

session = get_session(username=my_username, password=my_password)

m = get_match(session, 18786853)
```

And I get the following error:

```
Traceback (most recent call last):
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 280, in wrapped
    return function(session, *args, **kwargs)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 475, in get_match
    parsed = make_scrape_request(session, url)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 155, in make_scrape_request
    raise VooblyError('not logged in')
voobly.VooblyError: not logged in

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aa.py", line 9, in <module>
    m = get_match(session, 18786853)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 284, in wrapped
    return function(session, *args, **kwargs)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 475, in get_match
    parsed = make_scrape_request(session, url)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/voobly/__init__.py", line 155, in make_scrape_request
    raise VooblyError('not logged in')
voobly.VooblyError: not logged in
```

**Comment by happyleavesaoc** [comment]
That's no longer a valid match ID. Try a more recent one, like `21686419`. There may still be a login issue, but let's eliminate some variables.

**Comment by vhoulbreque** [comment]
I changed the match ID to `21686419`, and I still get the `voobly.VooblyError: not logged in`.  

Inside the `login` function, I made a `print(resp.content)`:

    try:
        session.get(session.auth.base_url + LOGIN_PAGE, timeout=REQ_TIMEOUT)
        print(session.auth.base_url + LOGIN_URL)
        resp = session.post(session.auth.base_url + LOGIN_URL, data={
            'username': session.auth.username,
            'password': session.auth.password
        })
        print("resp ", resp.content)
    except RequestException:
        raise VooblyError('failed to connect for login')

and this `resp.content` contains the HTML of the web page https://www.voobly.com/login/auth and the response code is 200

**Comment by happyleavesaoc** [comment]
Hmm, that is strange. Your code snippet works for me. Try:

1. Delete `voobly_cookies.pickle`, that's a cache of any cookies set during the login process.
2. Confirm that your username and password are correct.
3. Retry.

**Comment by vhoulbreque** [comment]
Ok, my mistake. I switched 2 letters from my username ^^"  
I ran the code again, and it worked. 
Thanks! :+1:
